kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runu]
    runtime_type = "io.containerd.runtime.v1.linux"
    runtime_engine = "/usr/bin/runu"
